FROM bcgovimages/von-image:node-1.12-2

ENV LOG_LEVEL ${LOG_LEVEL:-info}
ENV RUST_LOG ${RUST_LOG:-warning}

ADD --chown=indy:indy indy_config.py /etc/indy/

WORKDIR $HOME
ADD --chown=indy:indy bin bin
ADD --chown=indy:indy scripts scripts
